# Generated by Django 4.2.3 on 2023-08-18 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color code must be in the format #RRGGBB or #RGB.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('immune_against', models.ManyToManyField(blank=True, related_name='+', to='pokemon.pokemontype')),
                ('weak_against', models.ManyToManyField(blank=True, related_name='+', to='pokemon.pokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokemon.pokemontype')),
                ('secondary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokemon.pokemontype')),
            ],
        ),
    ]
